### ISSUE TITLE
Cyphernode's architecture

### ISSUE THREAD

**Issue by aitoribanez** [SatoshiPortal/cyphernode#100]
I have a question about cyphernode's architecture ( https://raw.githubusercontent.com/SatoshiPortal/cyphernode/dev/doc/CN-Arch.jpg )

For example, when we call to the API/gatekeeper (https://127.0.0.1:2009/v0/getbestblockhash) using curl. 

Cyphernode goes first to the gatekeeper. If the JWT credentials are valid, the request goes to the proxy. It looks where to send that request and it decide to send to the Bitcoin spender (I'm not sure here). The Bitcoin spender make the RPC request to bitcoin and send to the console the response. ¿Am I correct? Thanks! :-D

**Comment by Kexkey** [comment]
Hi @aitoribanez !

The bitcoin node response is sent to stdout which is assigned to a variable (for example, the `response` variable in the requesthandler) that is passed to `response_to_client` for it to be wrapped into a well-formed HTTP response with the required headers.  The stdout at that point is what is sent to the requester through netcat (see `startproxy.sh`) that has received the gatekeeper's http request.

Does that make more sense?  :)

**Comment by aitoribanez** [comment]
Hi @Kexkey !

Thanks for the quick answer. 

Make sense after make some echos on the code.

I will continue trying to make a new authentified endpoint for the API/keeper that gets the height of the chain.  :-)
