### ISSUE TITLE
Call bitcoin-cli inside Bitcoin container 

### ISSUE THREAD

**Issue by aitoribanez** [SatoshiPortal/cyphernode#101]
Hello @Kexkey !

I'm another time over here with another question :-D

This time I want to implement a new API endpoint that call to getmempoolinfo Bitcoin RPC.

I start trying to make this call inside bitcoin docker where bitcoin-cli is installed with this command:
```bitcoin-cli -rpcuser=rpc_username -rpcpassword=rpc_password --testnet getmempoolinfo ```

I dont change default Bitcoin RPC username and password [0] but I get:

```error: Authorization failed: Incorrect rpcuser or rpcpassword```

¿Where is bitcoin.conf file located inside Bitcoin docker container?

Thanks! :-D

[0] https://github.com/SatoshiPortal/cyphernode/blob/dev/proxy_docker/env.properties#L4

**Comment by Kexkey** [comment]
Hi @aitoribanez !

When you enter the container, make sure you are the cyphernode user.  So, instead of doing something like `docker exec -it 625 ash` you should do something like `docker exec -it 625 su-exec 1001:1001 ash` and then the bitcoin-cli command should work.

The bitcoin config file is in `/.bitcoin/`

**Comment by aitoribanez** [comment]
Thanks for the last reply!

I try entering bitcoin container like this:

``` docker exec -it dist_bitcoin_1 su-exec 1001:1001 sh```

The promt there has $ but ```whoami``` response with ```whoami: unknown uid 1001```. On /etc/passwd, cyphernode user doesnt exist.

If I type next to enter bitcoin container ```cd /.bitcoin/```,  I get permission error: ``` sh: cd: can't cd to /.bitcoin/: Permission denied```

Thanks!

**Comment by aitoribanez** [comment]
Entering to Bitcoin container as root, inside /.bitcoin/ is bitcoin.conf file and I see that the rpc user and password was different. I change that and I get the RPC response :-D

Entering the docker container with the ```su-exec 1001:1001``` also get response.

Thanks! :-D

**Comment by Kexkey** [comment]
For the record... 1001:1001 is the userid and groupid of the user that is running Cyphernode.  So if you chose to use the "cyphernode" user during install, have a look at the userid and groupid of that user on your machine and use it with su-exec.

If you want to propose your new endpoint to the project, it will be a pleasure to review and merge your pull request.

Thanks!

**Comment by aitoribanez** [comment]
My idea is to try with getmempoolinfo to get the way of how can a new endpoint could added to cyphernode. 
Then, I will help cyphernode adding new ones. 

Thanks! :-D
