### ISSUE TITLE
Add "gettxoutproof" endpoint

### ISSUE THREAD

**Issue by FrancisPouliot** [SatoshiPortal/cyphernode#168]
This is useful for claiming pegins with elements

gettxoutproof ["txid",...] ( "blockhash" )

Returns a hex-encoded proof that "txid" was included in a block.

NOTE: By default this function only works sometimes. This is when there is an
unspent output in the utxo for this transaction. To make it always work,
you need to maintain a transaction index, using the -txindex command line option or
specify the block in which the transaction is included manually (by blockhash).

Arguments:
1. txids          (json array, required) A json array of txids to filter
     [
       "txid",    (string) A transaction hash
       ...
     ]
2. blockhash      (string, optional) If specified, looks for txid in the block with this hash

Result:
"data"           (string) A string that is a serialized, hex-encoded data for the proof.

**Comment by phillamy** [comment]
Is there more to this issue than adding the endpoint and calling the watcher node with https://bitcoincore.org/en/doc/0.16.0/rpc/blockchain/gettxoutproof/ ?

**Comment by Kexkey** [comment]
Indeed, I think it's a pretty straightforward feature that will simply delegate the request to Bitcoin Core.  I guess for Cyphernode v0 API, it's ok to just respond as is Bitcoin Core's response.

**Comment by Kexkey** [comment]
https://github.com/SatoshiPortal/cyphernode/pull/234
