### ISSUE TITLE
Watchtxid return errror

### ISSUE THREAD

**Issue by Tomtibo** [SatoshiPortal/cyphernode#182]
Return the following error when a new watchtxid is requested. BUT the watch is working as expected.

Proxy logs:
```
2020-04-14T20:05:10+0000 22402 [watchtxidrequest] id_inserted: 34
./requesthandler.sh: line 476: syntax error: bad substitution
2020-04-14T20:05:10+0000 22402 Entering response_to_client()...
2020-04-14T20:05:11+0000 22402 [main] exiting
2020-04-14T20:05:11+0000 22402 [requesthandler] exiting
```

**Comment by Kexkey** [comment]
Hi @Tomtibo !  Yes, we are aware of the bug, @gabidi fixed it in his PR here: https://github.com/SatoshiPortal/cyphernode/pull/180

It will be merged soon.  In the meantime, you can fix the typo like this: https://github.com/SatoshiPortal/cyphernode/pull/180/files#diff-b76cf609b11d32f75478eb2f6775ebcfR329

Let me know if it works for you.  Thanks!

**Comment by Tomtibo** [comment]
OK thanks!

**Comment by Tomtibo** [comment]
Yes it's work, I've just added the missing '}'.
