### ISSUE TITLE
Spark wallet shows 0 balance after depositing BTC on-chain

### ISSUE THREAD

**Issue by ALeschinsky** [SatoshiPortal/cyphernode#189]
Fresh installation of cyphernode, wait until blockchain syncs, open https://127.0.0.1:2443/sparkwallet/#/deposit, send a transaction to the address generated, wait for transaction to get confirmed on the blockchain - the balance is supposed to appear in Spark wallet at this point, but I still have 0 btc shown, why? I want to uninstall cyphernode now, but I want to retrieve my funds back, how do I do that? Please help as I have some money lost now, I should have started with a smaller transaction :(

**Comment by ALeschinsky** [comment]
`echo "GET /getbalance" | docker run --rm -i --network=cyphernodenet alpine nc proxy:8888 -` prints:

`{"balance":0}`

`echo "GET /ln_getinfo" | docker run --rm -i --network=cyphernodenet alpine nc proxy:8888 -` prints:

```
{
   "id": "0304b13d52abf5127afe3077131e4ea5e21e204ea987344d4dd57c9bdf7d9e4849",
   "alias": "cyphernode notebook",
   "color": "40bf9d",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.8.2-51-g4bb7b46",
   "blockheight": 523926,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/.lightning/bitcoin",
   "warning_lightningd_sync": "Still loading latest blocks from bitcoind."
}
```

`"warning_lightningd_sync": "Still loading latest blocks from bitcoind."` - this looks bad, why is it stuck here? I restarted the whole thing with ./stop.sh + ./start.sh, the blockchain is fully synced...

**Comment by Kexkey** [comment]
Hi @ALeschinsky , don't worry, your funds will appear when the Bitcoin node is fully synced.  It has to sync until the time of the deposit to see the transaction.  Then, c-lightning and spark wallet will be able to show you the right balance.  You have to be patient, Bitcoin Core on mainnet can take several hours/days to be fully synced, depending on your hardware.
