### ISSUE TITLE
Add Bitcoin Network to Welcome app

### ISSUE THREAD

**Issue by Kexkey** [SatoshiPortal/cyphernode#268]
It would be very useful to know if we're running regtest, testnet or mainnet in the Bitcoin Core Node section of the Welcome app.

**Comment by filecommander** [comment]
I saw it in the features/cam branch here https://github.com/SatoshiPortal/cyphernode/blob/features/cam/cyphernodeconf_docker/lib/app.js.  If I'm not mistaken, @schulterklopfer added this.  Would you like to see the port # and network name ?

app.js:
    490:      port: (this.config.net === 'regtest') ? 18444 : ((this.config.net === 'testnet') ? 18333 : 8333)

**Comment by Kexkey** [comment]
Thanks @phillamy !  Merged to dev!
