### ISSUE TITLE
legacypay removed from Core Lightning v0.11.2

### ISSUE THREAD

**Issue by Kexkey** [SatoshiPortal/cyphernode#275]
Remove call to `legacypay` on Core Lightning since it's been removed in v0.11.2.

Code is in the `ln_pay` function in `proxy_docker/app/script/call_lightningd.sh`

Background: we used to first try `pay` (by default using MPP) and if this fails, we try to pay the invoice using `legacypay` because this doesn't use MPP and MPP sometimes causes routing problems.

**Comment by filecommander** [comment]
New features with v0.11.0

https://medium.com/blockstream/core-lightning-v0-11-0-channel-multiplexing-a-new-api-and-much-more-5d34df8cfeb5
