### ISSUE TITLE
Importing and watching an xpub

### ISSUE THREAD

**Issue by FrancisPouliot** [SatoshiPortal/cyphernode#50]
Purpose: we want to be able to give an xpub to cyphernode so that it can watch it and give notifications when bitcoins are sent to addresses derived from that xpu

Concerns:

- gap limit: this is designed with merchants in mind. It is possible that merchants generate 20 invoices with 20 addresses that remain unpaid. If this is the case, a wallet with a gap limit of 21 will not detect the payment.
- overload of Bitcoin Core: we don't want to crash bitcoin core
- address labelling: we want to have a system that makes it easy to group the keys derived from one xpub together
- usability: we want to be able to build features which allow people to obtain detailed and useful info on their xpubs

API endpoint:
- watchhdkey
- gethdkeyinfo

Parameters:
- derivation path: custom derivation path overriding default
- rescan: default set to true, this the is a parameter of `importmulti` `rescan`

**watchhdkey**

The client sends:
- xpub, ypub, zpub
- label
- derivation path
 Cyphernode
- save that xpub somewhere with the label and the path. No label by default. This will will allow apps to query information about xpubs by labels, so they dont have to manage the xpub-label database on their side.
- RPC call to Bitcoin Core `createwallet` with the label set as the the xpub by default and `disable_private_keys ` set to `true`
- Call to pycoin to derive 100 addresses : https://github.com/SatoshiPortal/cyphernode/blob/dev/pycoin_docker/script/pycoin.sh
- Bitcoin Core imports the 100 addresses using `importmulti` RPC call https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/importmulti/
- The label of each address is set as the xpub
- Cyphernode puts a watch on all the 100 addresses

Event: when cyphernode receives bitcoins at one of the addresses
- we add to the callback response: wallet name (xpub), derivation, label
- we check to see how many addresses there are left after this one in the derivation path. There should be always 100. So if for example there was a gap of 6, then there should be 93 ahdead and we should derive 7 more and import them into Bitcoin Core. So we are always deriving and adding new addresses as we see bitcoins coming in.

**gethdkeyinfo**
- Calls Bitcoin RPC `scantxoutset` for given derivation path (key info)
Returns:
key info: 

`Result:
{
  "unspents": [
    {
    "txid" : "transactionid",     (string) The transaction id
    "vout": n,                    (numeric) the vout value
    "scriptPubKey" : "script",    (string) the script key
    "amount" : x.xxx,             (numeric) The total amount in BTC of the unspent output
    "height" : n,                 (numeric) Height of the unspent transaction output
   }
   ,...], 
 "total_amount" : x.xxx,          (numeric) The total amount of all found unspent outputs in BTC
]`

- Get HDKEYINFO since import (all transactions that were processed by cyphernode)
- Call Bitcoin RPC `listtransactions
- parse transactions for those whose  `label` matches the `xpub

```
Result:
[
  {
    "address":"address",    (string) The bitcoin address of the transaction.
    "category":"send|receive", (string) The transaction category.
    "amount": x.xxx,          (numeric) The amount in BTC. This is negative for the 'send' category, and is positive
                                        for the 'receive' category,
    **"label"**: "label",       (string) A comment for the address/transaction, if any
    "vout": n,                (numeric) the vout value
    "fee": x.xxx,             (numeric) The amount of the fee in BTC. This is negative and only available for the 
                                         'send' category of transactions.
    "confirmations": n,       (numeric) The number of confirmations for the transaction. Negative confirmations indicate the
                                         transaction conflicts with the block chain
    "trusted": xxx,           (bool) Whether we consider the outputs of this unconfirmed transaction safe to spend.
    "blockhash": "hashvalue", (string) The block hash containing the transaction.
    "blockindex": n,          (numeric) The index of the transaction in the block that includes it.
    "blocktime": xxx,         (numeric) The block time in seconds since epoch (1 Jan 1970 GMT).
    "txid": "transactionid", (string) The transaction id.
    "time": xxx,              (numeric) The transaction time in seconds since epoch (midnight Jan 1 1970 GMT).
    "timereceived": xxx,      (numeric) The time received in seconds since epoch (midnight Jan 1 1970 GMT).
    "comment": "...",       (string) If a comment is associated with the transaction.
    "bip125-replaceable": "yes|no|unknown",  (string) Whether this transaction could be replaced due to BIP125 (replace-by-fee);
                                                     may be unknown for unconfirmed transactions not in the mempool
    "abandoned": xxx          (bool) 'true' if the transaction has been abandoned (inputs are respendable). Only available for the 
                                         'send' category of transactions.
  }
]
`
```

**Comment by Kexkey** [comment]
branch features/xpubswatch: https://github.com/SatoshiPortal/cyphernode/tree/features/xpubswatch

**Comment by FrancisPouliot** [comment]
closed because on branch xpubswatch
