### ISSUE TITLE
port 443 already in use

### ISSUE THREAD

**Issue by inpay** [SatoshiPortal/cyphernode#57]
ERROR: for gatekeeper  Cannot start service gatekeeper: driver failed programming external connectivity on endpoint dist_gatekeeper_1 (...): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

What if there's already a nginx server running? How to use cyphernode along with nginx?

**Comment by Kexkey** [comment]
The gatekeeper uses nginx to serve HTTP requests.  But it is a good idea to make the port configurable.  We'll add that to the next release.  Thanks!

In the meantime, you can manually change nginx configurations in the gatekeeper container to use the port you want.  If you want to use another nginx instance as an http entrypoint, you'll have to proxy the requests to the gatekeeper after having changed the port and it should work if well configured.

**Comment by schulterklopfer** [comment]
ACK :D

**Comment by schulterklopfer** [comment]
https://github.com/SatoshiPortal/cyphernode/pull/64

**Comment by Kexkey** [comment]
Tested and merged to dev branch.  Thanks!
