### ISSUE TITLE
Add OTS client and endpoints

### ISSUE THREAD

**Issue by FrancisPouliot** [SatoshiPortal/cyphernode#8]
We already have the python Open-Timestamps client dockerized, but I think it may actually be better to use the Javascript OTS client for this because AFAIK it already has everything we need to timestamp a hash directly without receiving a file that is hashed by the client.

This should be faily simple, we just need to implement the 4 functions:

- Stamp
- Upgrade
- Verify
- Info

Note: I don't think we need to add OTS calendars in Cyphernode. Having 3 calendars is enough, and too many calendars would create redundant spam.

This is a great ressource for this: 

- https://blog.eternitywall.com/2018/03/26/js-opentimestamps-by-example/

**Comment by Kexkey** [comment]
Stamp and upgrade implemented (with automatic upgrade and callbacks on upgraded stamp).  There's already an issue opened for Verify... should we open one for Info and close this one?
