### ISSUE TITLE
dist_lightning_1 cannot start because bitcoin.conf is a folder [macOS host]

### ISSUE THREAD

**Issue by darwin** [SatoshiPortal/cyphernode#83]
Just tried to generate and run my first cyphernode on macOS host from aea6b987d620f6314eaf60ee633ccf147538ebf9 using the wizard.

I have enabled support for lighting and selected docker-compose mode. Generation went ok. When I started it via `./start.sh` the docker container `dist_lightning_1` had trouble to start with

```
ERROR: for lightning  Cannot start service lightning: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/darwin/.cyphernode/lightning/bitcoin.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/6d60d2d7a9daa316635de1fbdd467c80865c842d8ec01eece38a6c1974dcbc7f/merged\\\" at \\\"/var/lib/docker/overlay2/6d60d2d7a9daa316635de1fbdd467c80865c842d8ec01eece38a6c1974dcbc7f/merged/.bitcoin/bitcoin.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
``` 

The problem is that something created `/Users/darwin/.cyphernode/lightning/bitcoin.conf/` as a directory prior `dist_lightning_1`. And when `dist_lightning_1` wanted to start it wanted to map the config file via:
```
    volumes:
      ...
      - "/Users/darwin/.cyphernode/lightning/bitcoin.conf:/.bitcoin/bitcoin.conf"
```

I'm not able to trouble shoot it right now. But something clearly gets confused creates a directory instead empty file or there are some extra trailing slashes with `cp` / `rsync`.

---

Host machine:
```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

> docker --version
Docker version 18.09.2, build 6247962

> docker-compose --version
docker-compose version 1.23.2, build 1110ad01
```

**Comment by schulterklopfer** [comment]
i seemed to have removed two file copies too much, when moving the spark wallet into the app zone. We're on it :-).
sorry for the inconvenience :-/

**Comment by schulterklopfer** [comment]
Ok. I think I fixed it. can you remove the whole "/Users/darwin/.cyphernode/lightning" folder and run setup.sh -irc (this will reconfigure and create all the files without asking the questions again). 
Let me know how it goes :)

**Comment by darwin** [comment]
I generated everything from scratch with ba00924de3e61ccf386a0dccd954b8737ad2d0ac. The problem is fixed. Thanks!
