### ISSUE TITLE
Change default address type and add config to setup

### ISSUE THREAD

**Issue by FrancisPouliot** [SatoshiPortal/cyphernode#94]
We should change the default address type to bech32 because we will need to have this anyway to integrate coinjoin.

This would affect:
- watches, and watchbyxpub
- get new address from spender
- pycoin derive utilities

I think it should be possible to change this config in the cyphernode configs

priority: high

**Comment by Kexkey** [comment]
All the derivations in Cyphernode already use the provided xpub to derive the good address type:

xpub/tpub = 1abc/mabc (P2PKH)
ypub/upub = 3abc/2abc (P2WPKH in P2SH)
zpub/vpub = bc1/tb1 (P2WPKH)

Ref.: https://github.com/satoshilabs/slips/blob/master/slip-0132.md#registered-hd-version-bytes

**Comment by Kexkey** [comment]
It is now possible to supply addresstype as an arg to getnewaddress like this:

`https://192.168.111.152:2009/getnewaddress/bech32` to get a bech32 address.

Currently in the `dev` github branch.

**Comment by tatiyaty** [comment]
https://xumoney.icu/refer.php?from=userarea.phphelenagillmore100@gmail.com

**Comment by Kexkey** [comment]
Released in v0.2.1.
