### ISSUE TITLE
Problem making a request through the gatekeeper

### ISSUE THREAD

**Issue by aitoribanez** [SatoshiPortal/cyphernode#98]
I'm having problems making requests through the gatekeeper. 

I try this command: 

"id="003";h64=$(echo -n "{\"alg\":\"HS256\",\"typ\":\"JWT\"}" | base64);p64=$(echo -n "{\"id\":\"$id\",\"exp\":$((`date +"%s"`+10))}" | base64);k="b9b8d527a1a27af2ad1697db3521f883760c342fc386dbc42c4efbb1a4d5e0af";s=$(echo -n "$h64.$p64" | openssl dgst -hmac "$k" -sha256 -r | cut -sd ' ' -f1);token="$h64.$p64.$s";curl -v -H "Authorization: Bearer $token" -k https://127.0.0.1/v0/getbestblockinfo" 

but I get "404 page not found" error. All the log here [0]. 

If I make the call direcly on the proxy (echo "GET /getbestblockinfo" | docker run --rm -i --network=cyphernodenet alpine nc proxy:8888 -) I get results.

   On https://localhost/welcome is all green except bitcoin feature but the node is update and syncing ok. If I use https://cyphernode on a request call on the machine cyphernode is running I get: "Could not resolve host: cyphernode" error.

¿Why could I get "404 page not found" making a request through the gatekeeper?

Thanks! :-D

[0] *   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: May 29 13:22:40 2019 GMT
*  expire date: May 28 13:22:40 2020 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a776d6d900)
> GET /v0/getbestblockinfo HTTP/2
> Host: 127.0.0.1
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMyIsImV4cCI6MTU1OTE0NTQ5MH0=.7f9ac409f785bba25c3d493f1ca7eacd151e8f3270b8a905c98519eb224f746c
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Wed, 29 May 2019 15:58:01 GMT
< 
404 page not found
* Connection #0 to host 127.0.0.1 left intact

**Comment by aitoribanez** [comment]
The problem was apache2. 

It was on and blocking port 443 as I could see with this commad: ```sudo lsof -i -P -n | grep LISTEN```

**Comment by aitoribanez** [comment]
I'm having problems making requests through the gatekeeper. 

I try this command: 

"id="003";h64=$(echo -n "{\"alg\":\"HS256\",\"typ\":\"JWT\"}" | base64);p64=$(echo -n "{\"id\":\"$id\",\"exp\":$((`date +"%s"`+10))}" | base64);k="b9b8d527a1a27af2ad1697db3521f883760c342fc386dbc42c4efbb1a4d5e0af";s=$(echo -n "$h64.$p64" | openssl dgst -hmac "$k" -sha256 -r | cut -sd ' ' -f1);token="$h64.$p64.$s";curl -v -H "Authorization: Bearer $token" -k https://127.0.0.1/v0/getbestblockinfo" 

but I get "404 page not found" error. All the log here [0]. 

If I make the call direcly on the proxy (echo "GET /getbestblockinfo" | docker run --rm -i --network=cyphernodenet alpine nc proxy:8888 -) I get results.

   On https://localhost/welcome is all green except bitcoin feature but the node is update and syncing ok. If I use https://cyphernode on a request call on the machine cyphernode is running I get: "Could not resolve host: cyphernode" error.

¿Why could I get "404 page not found" making a request through the gatekeeper?

Thanks! :-D


[0] *   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: May 29 13:22:40 2019 GMT
*  expire date: May 28 13:22:40 2020 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a776d6d900)
> GET /v0/getbestblockinfo HTTP/2
> Host: 127.0.0.1
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAwMyIsImV4cCI6MTU1OTE0NTQ5MH0=.7f9ac409f785bba25c3d493f1ca7eacd151e8f3270b8a905c98519eb224f746c
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Wed, 29 May 2019 15:58:01 GMT
< 
404 page not found
* Connection #0 to host 127.0.0.1 left intact

**Comment by Kexkey** [comment]
Hi @aitoribanez 

Try with https://127.0.0.1:2009/v0/getbestblockinfo, you should have more luck.  A lot of stuff changed in the last releases and unfortunately some info in the docs didn't follow.

Port 443 is used by traefik for accessing the "cypherapps", which are the web applications using cyphernode.  The welcome app and Spark Wallet are cypherapps that are accessible through traefik, on port 443.

But the Cyphernode API (the gatekeeper) is listening on port 2009.

Also, if you want to use https://cyphernode as the url, you have to have "cyphernode" in your hosts file (with the good IP address) or use a DNS server that will know what's the IP address for "cyphernode".

Don't forget to change "b9b8d527a1a27af2ad1697db3521f883760c342fc386dbc42c4efbb1a4d5e0af" with your generated key, found in your encrypted client.7z file (downloadable from the welcome web page) or found in the keys.properties file found inside the installed cyphernode/gatekeeper directory on the host.

Let me know if it fixes your problems!

Thanks for the issue, I'll improve the docs!

**Comment by aitoribanez** [comment]
First for all thanks @Kexkey  for the information and the last reply! :-D

I try with this command:
"id="003";h64=$(echo -n "{"alg":"HS256","typ":"JWT"}" | base64);p64=$(echo -n "{"id":"$id","exp":$((date +"%s"+10))}" | base64);k="b9b8d527a1a27af2ad1697db3521f883760c342fc386dbc42c4efbb1a4d5e0af";s=$(echo -n "$h64.$p64" | openssl dgst -hmac "$k" -sha256 -r | cut -sd ' ' -f1);token="$h64.$p64.$s";curl -v -H "Authorization: Bearer $token" -k https://127.0.0.1:2009/v0/getbestblockinfo" and I get 402 forbidden. Here [0] is the log.

If I make as bash client do (https://github.com/SatoshiPortal/cyphernode/blob/dev/clients/shell/cyphernode-client.sh) with their credentials (https://github.com/SatoshiPortal/cyphernode/blob/dev/clients/shell/cyphernode.conf) as:
- ```p64=$(echo -n "{\"id\":\"${id}\",\"exp\":$((`date +"%s"`+10))}" | base64)```
- ```s=$(echo -n "$h64.$p64" | openssl dgst -hmac "$key" -sha256 -r | cut -sd ' ' -f1)```
- ```token="$h64.$p64.$s"```
- ```curl -v -H "Authorization: Bearer $token" -k "https://127.0.0.1:2009/v0/getbestblockinfo"```

I get 402 forbidden too. :-D

¿Any ideas?

[0] bash: date +%s+10: syntax error: operand expected (error token is "%s+10")
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 2009 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=cyphernodehost
*  start date: May 29 00:17:33 2019 GMT
*  expire date: May 26 00:17:33 2029 GMT
*  issuer: CN=cyphernodehost
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /v0/getbestblockinfo HTTP/1.1
> Host: 127.0.0.1:2009
> User-Agent: curl/7.58.0
> Accept: */*
> Authorization: Bearer e2FsZzpIUzI1Nix0eXA6SldUfQ==..5d9f67fee6c587585da2b3041ed50d930aa9a777f559052db4fa6f90e1a12aa8
> 
< HTTP/1.1 403 Forbidden
< Server: nginx/1.15.10
< Date: Wed, 29 May 2019 19:56:12 GMT
< Content-Type: text/html
< Content-Length: 154
< Connection: keep-alive
< 
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.15.10</center>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact

**Comment by Kexkey** [comment]
Hi @aitoribanez 

The `403 Forbidden` response means your JWT is not good.  You need to replace the key `b9b8d527a1a27af2ad1697db3521f883760c342fc386dbc42c4efbb1a4d5e0af` with your generated key.  That `b9b8d5...` key is just an example for the docs.

To find your generated keys, look in the file certs.7z (you need your cyphernode admin passphrase you entered when running cyphernode setup to decrypt that file) for the file called `keys.txt` and you will find your keys in there.  Use ID `003` (admin role) to make sure you can access all the API functions.

You can download that file from your welcome page, https://127.0.0.1/welcome :

<img width="932" alt="Screen Shot 2019-05-29 at 4 31 58 PM" src="https://user-images.githubusercontent.com/15161742/58589586-3c1bb280-8230-11e9-9ff2-0da489517322.png">

**Comment by aitoribanez** [comment]
I download certs.7z from https://127.0.0.1/welcome/certs.7z. When unzipped, add the password and I open keys.txt. Take the token for 003 and call to the same command but with this token:

id="003";h64=$(echo -n "{"alg":"HS256","typ":"JWT"}" | base64);p64=$(echo -n "{"id":"$id","exp":$((date +"%s"+10))}" | base64);k="TOKEN";s=$(echo -n "$h64.$p64" | openssl dgst -hmac "$k" -sha256 -r | cut -sd ' ' -f1);token="$h64.$p64.$s";curl -v -H "Authorization: Bearer $token" -k https://127.0.0.1:2009/v0/getbestblockinfo"

but I still get 403 forbidden.

**Comment by aitoribanez** [comment]
Today I try another time. I see that the command give an error:

"bash: date +%s+10: syntax error: operand expected (error token is "%s+10")" and $h64 gets empty. 

I see that your original call has apostrophes inside date and that was the problem of the error. After change that on the command, I started getting results! :-D

Here [0] the command I use:

id="003";h64=$(echo -n "{\"alg\":\"HS256\",\"typ\":\"JWT\"}" | base64);p64=$(echo -n "{\"id\":\"$id\",\"exp\":$((`date +"%s"`+10))}" | base64);k="KEY";s=$(echo -n "$h64.$p64" | openssl dgst -hmac "$k" -sha256 -r | cut -sd ' ' -f1);token="$h64.$p64.$s";curl -v -H "Authorization: Bearer $token" -k https://127.0.0.1:2009/v0/getbestblockhash

Two more questions:

- To call to the gatekeeper I could use JS or bash clients (https://github.com/SatoshiPortal/cyphernode/tree/master/clients) to call from server or client (web application) ¿right?

- cyphernode runs well on a raspberry pi 3b+ with the block data previously synced with or without prunning ¿right?

Thank you very much! :-D

**Comment by Kexkey** [comment]
Good, happy to hear that it works!  Yes, the reverse apostrophes were important.

You can use any language as the gatekeeper's client.  We have examples in the clients/ to start with and you can also see how the Welcome App is built as a Golang client.

Yes, cyphernode runs on a RPi.  I run it on a RPi 2 as well as 3.  You definitely should pre-sync the Bitcoin data on another machine though, since the Pi is pretty slow.  If you set cyphernode to use a pruned bitcoin node, you won't be able to use Lightning Network and won't have the "fees" on watched transactions.  Better to have a full archival node.  I use LVM2 to combine multiple USB sticks into one big storage device.

**Comment by aitoribanez** [comment]
I will continue traying with the client on JS. 
Then I want to a more calls to Bitcoin RPC inside cyphernode.

Thanks for all! I will open an issue, when I'm in trubbles! :-D
